import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import { Provider } from "react-redux";
import store from "@/redux/store";
import ClientProvider from "./reduxGlobal";


const poppins = Poppins({
  subsets: ['latin'], 
  weight: ['300', '400', '500', '600', '700'], 
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <ClientProvider >
        {children}
        </ClientProvider>
      </body>
    </html>
  );
}
